<?xml version="1.0" encoding="utf-8"?><Database Name="DatTiec" Class="dbDatTiecDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=DatTiec;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatTiecConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="UserAdmin" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PassAdmin" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Buoi" Member="Buois">
    <Type Name="Buoi">
      <Column Name="MaBuoi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BuoiToChuc" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Buoi_DonDatTiecNhap" Member="DonDatTiecNhaps" ThisKey="MaBuoi" OtherKey="MaBuoi" Type="DonDatTiecNhap" />
      <Association Name="Buoi_DonDatTiec" Member="DonDatTiecs" ThisKey="MaBuoi" OtherKey="MaBuoi" Type="DonDatTiec" />
    </Type>
  </Table>
  <Table Name="dbo.CTDonDat" Member="CTDonDats">
    <Type Name="CTDonDat">
      <Column Name="MaDD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaMonAn" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DonDatTiec_CTDonDat" Member="DonDatTiec" ThisKey="MaDD" OtherKey="MaDD" Type="DonDatTiec" IsForeignKey="true" />
      <Association Name="ThucDon_CTDonDat" Member="ThucDon" ThisKey="MaMonAn" OtherKey="MaMonAn" Type="ThucDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhGia" Member="DanhGias">
    <Type Name="DanhGia">
      <Column Name="MaDanhGia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DonDatTiecNhap" Member="DonDatTiecNhaps">
    <Type Name="DonDatTiecNhap">
      <Column Name="MaNhap" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SLKhach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaBuoi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayToChuc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaHinhThuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Buoi_DonDatTiecNhap" Member="Buoi" ThisKey="MaBuoi" OtherKey="MaBuoi" Type="Buoi" IsForeignKey="true" />
      <Association Name="HinhThuc_DonDatTiecNhap" Member="HinhThuc" ThisKey="MaHinhThuc" OtherKey="MaHinhThuc" Type="HinhThuc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonDatTiec" Member="DonDatTiecs">
    <Type Name="DonDatTiec">
      <Column Name="MaDD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTenKH" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SLKhach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayToChuc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaHinhThuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaSanh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaBuoi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DonDatTiec_CTDonDat" Member="CTDonDats" ThisKey="MaDD" OtherKey="MaDD" Type="CTDonDat" />
      <Association Name="DonDatTiec_HoaDon" Member="HoaDons" ThisKey="MaDD" OtherKey="MaDD" Type="HoaDon" />
      <Association Name="Buoi_DonDatTiec" Member="Buoi" ThisKey="MaBuoi" OtherKey="MaBuoi" Type="Buoi" IsForeignKey="true" />
      <Association Name="HinhThuc_DonDatTiec" Member="HinhThuc" ThisKey="MaHinhThuc" OtherKey="MaHinhThuc" Type="HinhThuc" IsForeignKey="true" />
      <Association Name="NhanVien_DonDatTiec" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
      <Association Name="Sanh_DonDatTiec" Member="Sanh" ThisKey="MaSanh" OtherKey="MaSanh" Type="Sanh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HinhThuc" Member="HinhThucs">
    <Type Name="HinhThuc">
      <Column Name="MaHinhThuc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HinhThucToChuc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="HinhThuc_DonDatTiecNhap" Member="DonDatTiecNhaps" ThisKey="MaHinhThuc" OtherKey="MaHinhThuc" Type="DonDatTiecNhap" />
      <Association Name="HinhThuc_DonDatTiec" Member="DonDatTiecs" ThisKey="MaHinhThuc" OtherKey="MaHinhThuc" Type="DonDatTiec" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DonDatTiec_HoaDon" Member="DonDatTiec" ThisKey="MaDD" OtherKey="MaDD" Type="DonDatTiec" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiThucDon" Member="LoaiThucDons">
    <Type Name="LoaiThucDon">
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LoaiThucDon_ThucDon" Member="ThucDons" ThisKey="MaLoai" OtherKey="MaLoai" Type="ThucDon" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_DonDatTiec" Member="DonDatTiecs" ThisKey="MaNV" OtherKey="MaNV" Type="DonDatTiec" />
    </Type>
  </Table>
  <Table Name="dbo.Sanh" Member="Sanhs">
    <Type Name="Sanh">
      <Column Name="MaSanh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSanh" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Hinh" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="Sanh_DonDatTiec" Member="DonDatTiecs" ThisKey="MaSanh" OtherKey="MaSanh" Type="DonDatTiec" />
    </Type>
  </Table>
  <Table Name="dbo.ThucDon" Member="ThucDons">
    <Type Name="ThucDon">
      <Column Name="MaMonAn" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenMonAn" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Hinh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ThucDon_CTDonDat" Member="CTDonDats" ThisKey="MaMonAn" OtherKey="MaMonAn" Type="CTDonDat" />
      <Association Name="LoaiThucDon_ThucDon" Member="LoaiThucDon" ThisKey="MaLoai" OtherKey="MaLoai" Type="LoaiThucDon" IsForeignKey="true" />
    </Type>
  </Table>
</Database>